CREATE TABLE health_general_data_informatives (
    name VARCHAR(240) NOT NULL PRIMARY KEY
);

INSERT INTO health_general_data_informatives
VALUES 
    ('Pessoas que apresentaram algum dos sintoma(s) (mil pessoas)'),
    ('CV - Pessoas que apresentaram algum dos sintoma(s) (%)'),
    ('Distribuição das pessoas que apresentaram algum dos sintoma(s) (%)'),
    ('CV - Distribuição das pessoas que apresentaram algum dos sintoma(s) (%)'),
    ('Percentual de pessoas que apresentaram algum dos sintomas no total da população (%) '),
    ('CV - Percentual de pessoas que apresentaram algum dos sintomas no total da população (%) '),
    ('Pessoas que apresentaram o sintoma de perda de cheiro ou de sabor (mil pessoas)'),
    ('CV - Pessoas que apresentaram o sintoma de perda de cheiro ou de sabor (%)'),
    ('Distribuição das pessoas que apresentaram o sintoma de perda de cheiro ou de sabor (%)'),
    ('CV - Distribuição das pessoas que apresentaram o sintoma de perda de cheiro ou de sabor (%)'),
    ('Pessoas que apresentaram os sintomas de tosse, febre e dificuldade para respirar (mil pessoas) '),
    ('CV - Pessoas que apresentaram os sintomas de tosse, febre e dificuldade para respirar (%) '),
    ('Distribuição das pessoas que apresentaram os sintomas de tosse, febre e dificuldade para respirar (%) '),
    ('CV - Distribuição das pessoas que apresentaram os sintomas de tosse, febre e dificuldade para respirar (%)'),
    ('Pessoas que apresentaram os sintomas de tosse, febre e dor no peito (mil pessoas)'),
    ('CV - Pessoas que apresentaram os sintomas de tosse, febre e dor no peito (%) '),
    ('Distribuição das pessoas que apresentaram os sintomas de tosse, febre e dor no peito (%)'),
    ('CV - Distribuição das pessoas que apresentaram os sintomas de tosse, febre e dor no peito (%)'),
    ('Pessoas que apresentaram sintomas referenciados conjugados3 (mil pessoas)'),
    ('CV - Pessoas que apresentaram sintomas referenciados conjugados3 (%) '),
    ('Distribuição das pessoas que apresentaram sintomas referenciados conjugados3 (%)'),
    ('CV - Distribuição das pessoas que apresentaram sintomas referenciados conjugados3 (%)'),
    ('Percentual de pessoas que apresentaram o sintoma de perda de cheiro ou de sabor no total da população (%)'),
    ('CV – Percentual de pessoas que apresentaram o sintoma de perda de cheiro ou de sabor no total da população (%) '),
    ('Percentual de pessoas que apresentaram os sintomas de tosse, febre e dificuldade para respirar no total da população (%) '),
    ('CV - Percentual de pessoas que apresentaram os sintomas de tosse, febre e dificuldade para respirar no total da população (%)'),
    ('Percentual de pessoas que apresentaram os sintomas de tosse, febre e dor no peito no total da população (%)'),
    ('CV - Percentual de pessoas que apresentaram os sintomas de tosse, febre e dor no peito no total da população (%)'),
    ('Percentual de pessoas que apresentaram sintomas referenciados conjugados3 no total da população (%)'),
    ('CV - Percentual de pessoas que apresentaram sintomas referenciados conjugados3 no total da população (%)'),
    ('Pessoas que procuraram estabelecimento de saúde e que apresentaram algum dos sintomas (mil pessoas)'),
    ('CV - Pessoas que procuraram estabelecimento de saúde e que apresentaram algum dos sintomas (%)'),
    ('Percentual de pessoas que procuraram estabelecimento de saúde entre aquelas que apresentaram algum dos sintomas (%)'),
    ('CV - Percentual de pessoas que procuraram estabelecimento de saúde entre aquelas que apresentaram algum dos sintomas (%)'),
    ('Pessoas que procuraram estabelecimento de saúde e apresentaram sintomas referenciados conjugados3 (mil pessoas) '),
    ('CV - Pessoas que procuraram estabelecimento de saúde e apresentaram sintomas referenciados conjugados3 (%) '),
    ('Percentual de pessoas que procuraram estabelecimento de saúde entre aquelas que apresentaram sintomas referenciados conjugados3 (%) '),
    ('CV - Percentual de pessoas que procuraram estabelecimento de saúde entre aquelas que apresentaram sintomas referenciados conjugados3 (%) '),
    ('Pessoas que procuraram atendimento de saúde em hospital (mil pessoas)'),
    ('CV - Pessoas que procuraram atendimento de saúde em hospital (%)'),
    ('Distribuição das pessoas que procuraram atendimento de saúde em hospital (%)'),
    ('CV – Distribuição das pessoas que procuraram atendimento de saúde em hospital (%)'),
    ('Percentual de pessoas que procuraram atendimento de saúde em hospital, entre aquelas que procuraram estabelecimento de saúde (%) '),
    ('CV - Percentual de pessoas que procuraram atendimento de saúde em hospital, entre aquelas que procuraram estabelecimento de saúde (%) '),
    ('Pessoas que procuraram atendimento de saúde em hospital e que apresentaram sintomas referenciados conjugados3 (mil pessoas)'),
    ('CV - Pessoas que procuraram atendimento de saúde em hospital e que apresentaram sintomas referenciados conjugados3 (%)'),
    ('Distribuição das pessoas que procuraram atendimento de saúde em hospital e que apresentaram sintomas referenciados conjugados3 (%)'),
    ('CV – Distribuição das pessoas que procuraram atendimento de saúde em hospital e que apresentaram sintomas referenciados conjugados3 (%)'),
    ('Percentual de pessoas que procuraram atendimento de saúde em hospital, entre aquelas que procuraram estabelecimento de saúde e apresentaram algum dos sintomas referenciados conjugados3 (%)'),
    ('CV – Percentual de pessoas que procuraram atendimento de saúde em hospital, entre aquelas que procuraram estabelecimento de saúde e apresentaram algum dos sintomas referenciados conjugados3 (%)'),
    ('Pessoas que foram internadas e que procuraram hospital (mil pessoas)'),
    ('CV - Pessoas que foram internadas e que procuraram hospital (%)'),
    ('Distribuição das pessoas que foram internadas e que procuraram hospital (%)'),
    ('CV - Distribuição das pessoas que foram internadas e que procuraram hospital (%)'),
    ('Percentual de pessoas que foram internadas entre aquelas que procuraram  hospital (%)'),
    ('CV - Percentual de pessoas que foram internadas entre aquelas que procuraram  hospital (%)'),
    ('Pessoas que foram internadas em hospital e ficaram sedadas, intubadas e com respiração artificial (mil pessoas) '),
    ('CV - Pessoas que foram internadas em hospital e ficaram sedadas, intubadas e com respiração artificial (%) '),
    ('Distribuição das pessoas que foram internadas em hospital e ficaram sedadas, intubadas e com respiração artificial (%) '),
    ('CV – Distribuição das pessoas que foram internadas em hospital e ficaram sedadas, intubadas e com respiração artificial (%) '),
    ('Percentual de pessoas que foram internadas e ficaram sedadas, intubadas e com respiração artificial, entre aquelas que ficaram internadas em hospital (%)'),
    ('CV - Percentual de pessoas que foram internadas e ficaram sedadas, intubadas e com respiração artificial, entre aquelas que ficaram internadas em hospital (%)'),
    ('Pessoas que foram internadas entre aquelas que procuraram hospital e apresentaram sintomas referenciados conjugados3 (mil pessoas)'),
    ('CV - Pessoas que foram internadas entre aquelas que procuraram hospital e apresentaram sintomas referenciados conjugados3 (%) '),
    ('Distribuição das pessoas que foram internadas entre aquelas que procuraram hospital e apresentaram sintomas referenciados conjugados3 (%)'),
    ('CV - Distribuição das pessoas que foram internadas entre aquelas que procuraram hospital e apresentaram sintomas referenciados conjugados3 (%)'),
    ('Percentual de pessoas que foram internadas entre aquelas que procuraram hospital e apresentaram sintomas referenciados conjugados3 (%) '),
    ('CV - Percentual de pessoas que foram internadas entre aquelas que procuraram hospital e apresentaram sintomas referenciados conjugados3 (%) '),
    ('População residente (mil pessoas)'),
    ('CV - População residente (%)'),
    ('Distribuição da população residente (%)'),
    ('CV - Distribuição da população residente (%)'),
    ('Domicílios (mil domicílios)'), 
    ('CV – Domicílios (%) '),
    ('Distribuição de domicílios (%)'),
    ('CV – Distribuição de domicílios (%)'),
    ('Pessoas que não procuraram atendimento em estabelecimento de saúde (mil pessoas)'),
    ('CV - Pessoas que não procuraram atendimento em estabelecimento de saúde (%)'),
    ('Percentual das pessoas que não procuraram atendimento em estabelecimento de saúde (%)'),
    ('CV - Percentual das pessoas que não procuraram atendimento em estabelecimento de saúde (%)'),
    ('Pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus (mil pessoas)'),
    ('CV - Pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus (%)'),
    ('Distribuição das pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus no total de pessoas que fizeram algum teste (%)'),
    ('CV - Distribuição das pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus no total de pessoas que fizeram algum teste (%)'),
    ('Percentual de pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus no total da população (%)'),
    ('CV - Percentual de pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus no total da população (%)'),
    ('Pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus e testaram positivo (mil pessoas) '),
    ('CV - Pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus e testaram positivo (%) '),
    ('Distribuição das pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus e testaram positivo, no total de pessoas que testaram positivo  (%) '),
    ('CV - Distribuição das pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus e testaram positivo, no total de pessoas que testaram positivo  (%) '),
    ('Percentual de pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus e testaram positivo, no total da população (%) '),
    ('CV - Percentual de pessoas que fizeram algum teste para saber se estavam infectadas pelo Coronavírus e testaram positivo, no total da população (%) '),
    ('Pessoas que fizeram o teste SWAB (mil pessoas)'),
    ('CV - Pessoas que fizeram o teste SWAB (%)'),
    ('Distribuição de pessoas que fizeram o teste SWAB segundo o resultado do exame  no total de pessoas que fizeram o teste (%)'),
    ('CV - Distribuição de pessoas que fizeram o teste SWAB segundo o resultado do exame  no total de pessoas que fizeram o teste (%)'),
    ('Pessoas que fizeram o exame de sangue com furo no dedo (mil pessoas)'),
    ('CV - Pessoas que fizeram o exame de sangue com furo no dedo (%)'),
    ('Distribuição das Pessoas que fizeram o exame de sangue com furo no dedo no total de pessoas que fizeram esse teste (%)'),
    ('CV - Distribuição das Pessoas que fizeram o exame de sangue com furo no dedo no total de pessoas que fizeram esse teste (%)'),
    ('Pessoas que fizeram o exame de sangue através da veia do braço (mil pessoas) '),
    ('CV - Pessoas que fizeram o exame de sangue através da veia do braço (%) '),
    ('Distribuição de pessoas que fizeram o exame de sangue através da veia do braço (%)'),
    ('CV - Distribuição de pessoas que fizeram o exame de sangue através da veia do braço (%)'),
    ('Pessoas com diagnóstico médico de alguma comorbidade (mil pessoas) '),
    ('CV - Pessoas com diagnóstico médico de alguma comorbidade (%) '),
    ('Percentual de pessoas com diagnóstico médico de alguma comorbidade no total da população (%) '),
    ('CV - Percentual de pessoas com diagnóstico médico de alguma comorbidade no total da população (%) '),
    ('Pessoas com alguma comorbidade e que testaram positivo em algum dos testes (mil pessoas)'),
    ('CV - Pessoas com alguma comorbidade e que testaram positivo em algum dos testes (%)'),
    ('Percentual de pessoas com alguma comorbidade e que testaram positivo em algum dos testes no total de pessoas com alguma comorbidade (%) '),
    ('CV - Percentual de pessoas com alguma comorbidade e que testaram positivo em algum dos testes no total de pessoas com alguma comorbidade (%) )');